plugins {
    id 'com.android.application'
}

android {
    namespace 'ua.bombarena.app'
    compileSdk 34
    defaultConfig {
        applicationId "ua.bombarena.app"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.2.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig false
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
